### ISSUE TITLE
Sensor not updating

### ISSUE THREAD

**Issue by GervaisdeM** [custom-components/sensor.file_restore#4]
I'm having an issue where the setting for the target_temp never changes. It only updates when home assistant starts or if I make a change. For example, if I set the system from off to heat. I added a scan interval to my sensor to see if I can force it to update hourly, but it has the same behaviour with our without that setting. Am I missing something?

I've configured my sensor as follows:
```
climate:
  - platform: programmable_thermostat
    name: Bedroom Heater
    heater:
      - switch.switch4
    actual_temp_sensor: sensor.master_bedroom_temperature
    min_temp: 14
    max_temp: 18
    target_temp_sensor: sensor.thermostat_program
    tolerance: 0.3
    hvac_options: 7
    auto_mode: all

sensor:
  - platform: file_restore
    unit_of_measurement: '°C'
    file_path: '/etc/homeassistant/file_restore/thermostat_program.csv'
    name: Thermostat Program
    length: day
    detail: hour
    scan_interval: 60
```

And my file looks as follows:
```
gervais@grater (master)✗ % cat /etc/homeassistant/file_restore/thermostat_program.csv                                                                      /etc/homeassistant
# One entry per hour
17, 14, 14, 14, 14, 15, 17, 18, 16, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15.5, 16.5, 17.5, 18
```
